version: '3.8'

services:
  front:
    image: front:prod
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      no_cache: true
    ports:
      - "5173:80"
    depends_on:
      - server
  server:
    image: server:prod
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.prod
      no_cache: true
    ports:
      - "8000:8000"
